---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kingstemple-in
  namespace: default
spec:
  secretName: kingstemple-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kingstemple.in"
  dnsNames:
  - "kingstemple.in"
  - "wwww.kingstemple.in"